plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nexus.universalbridge.finalapp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nexus.universalbridge.finalapp'
        minSdk 26
        targetSdk 35
        versionCode 210
        versionName '2.1.0'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
